#### main
%$function_name_caps$ - $one_line_description$
@if $has_multi_line_description$=1
$multi_line_description$
@end if
%
% Syntax:  [$output_parameter_list$] = $function_name$($input_parameter_list$)
%
% Inputs:
@foreach input
%    $pname$ - $complex_space$$dtype$ ($dimensions$)
@end foreach input
%
% Outputs:
@foreach output
%    $pname$ - $complex_space$$dtype$ ($dimensions$)
@end foreach output
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
#### end