%SQUARE_IT - 
%
% Syntax:  [y_output] = square_it(x_input)
%
% Inputs:
%    x_input - double (1,N)
%
% Outputs:
%    y_output - double (1,N)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
